# Hyperparameters
train_batch_size: 128
val_batch_size: ${train_batch_size}
learning_rate: 2e-4

# Dataset
dataset_path: ./data/grid/processed/
train_split_size: 0.8
input_image_height: 96
input_image_width: 96
output_image_height: ${input_image_height}
output_image_width: ${input_image_width}
audio_freq: 16000
mfcc_winlen: 0.025
mfcc_winstep: 0.01
mfcc_n: 13

# Model
model:
    _target_: networks.baseline.UNetFusion
    learning_rate: ${learning_rate}

# Training
gpus: 1
precision: 16
data_loader_workers: null  # Set to max CPU cores

# Checkpointing
checkpoint:
    save_top_k: 3
    monitor: val_loss
    mode: min

# Logging
logs:
    path: '../logs/'
    use_comet: False
